<footer>
    <div class="footer-content">
        <a href="mailto:Info@Commercalify.com">Info@Commercalify.com</a>
        <div class="links">
            <a href="https://webtechprojecthbnccl.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiYjcwY2U5ZWMyMDAzNDdmOThkMjVhM2UwYTcxODViZmEiLCJwIjoiaiJ9 "
                target="_blank">Jira</a>
            <a href="https://github.com/Hennyy-B/Web_TechProject.git" target="_blank">GitHub</a>
        </div>
    </div>
</footer>